company_title = "Stealth Startup"
submitted_date = "08/24/2024"
location = "Remote"
role = "Full Stack Engineer"
level = "Associate"
skills = [
    "Angular",
    "Back-End Web Development",
    "Cascading Style Sheets (CSS)",
    "Front-End Development",
    "HTML",
    "JavaScript",
    "Code Review",
    "Coding Standards",
    "Emerging Trends",
    "Problem Solving",
]
remote = true
platform = "linkedin"
link = "https://www.linkedin.com/jobs/view/4009565413/?refId=ByteString(length%3D16%2Cbytes%3D6190533f...8df7c788)&trackingId=zNeoebyqn46%2FfwmGyw3Siw%3D%3D"

[status]
date = "08/24/2024"
kind = "waiting to hear back"
explanation = "applied and am waiting to hear back"

[[events]]
date = "08/24/2024"
kind = "applied"
explanation = "This job was recommended to me by linkedin since I had matching skillsets. I applied."

[[events]]
date = "08/25/2024"
kind = "follow-up voicemail"
explanation = "Left a voice message for Penn State Career services at 814-865-2377, @ 7:51am. Received a rejection before this but I followed up anyways to see if I could get my application looked at. My experiences, interest, and availability align, and I have certs too."

[[events]]
date = "08/25/2024"
kind = "follow-up email"
explanation = "I emailed clr277@psu.edu to let them know I followed up with IT Support role via voicemail."

[resume]
filename = "1-pager-2024-08-16-chris-dillinger.pdf"
filepath = "/home/c/projects/github.com/1nf053c/notemate/resumes/pdf/1-pager-2024-08-16-chris-dillinger.pdf"

[company_title_clear]
status = "poor"
reason = "not listed"

[job_title_clear]
status = "ok"
reason = "ok"

[required_skills_clear]
status = "ok"
reason = """
ok
"""
