abstract = '''
TEXT
'''

introduction = '''
TEXT
'''

establishing_territory = '''
TEXT
'''

establishing_niche = '''
TEXT
'''

occupying_niche = '''
TEXT
'''

literature_review = '''
TEXT
'''

methodology = '''
TEXT
'''

results = '''
TEXT
'''

discussion = '''
TEXT
'''

introduction_of_findings = '''
TEXT
'''

evaluation = '''
TEXT
'''
